Header header
# Amps measured at the input of the motor controller
float64 motor_amps_in
# Amps measured at the output of the motor controller
float64 motor_amps_out
# Voltage measured at the (power) input of the motor controller
float64 motor_voltage_in
# Voltage measured at the output of the motor controller
float64 motor_voltage_out
# A string dispalying the status of the motor controller
string motor_status
